name: Publish

on:
  push:
    tags: '**'

jobs:
  publish:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { name: win_x64, os: windows-latest, runtime: win-x64 }
          - { name: win_arm64, os: windows-latest, runtime: win-arm64 }
          - { name: linux_x64, os: ubuntu-latest, runtime: linux-x64 }
          - { name: mac_x64, os: macos-latest, runtime: osx-x64 }
          - { name: mac_arm64, os: macos-latest, runtime: osx-arm64 }

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.config.runtime }}
        working-directory: ./Source/AssetRipper-Console/

      - name: List Files
        shell: bash
        run: ls -R ./Source/AssetRipper-Console/bin/Release/${{ matrix.config.runtime }}/publish

      - name: List Files
        shell: bash
        run: date -u > ./Source/AssetRipper-Console/bin/Release/${{ matrix.config.runtime }}/publish/compile_time.txt

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          prerelease: false
          title: "AssetRipper_${{ matrix.config.name }}"
          files: |
            ./Source/AssetRipper-Console/bin/Release/${{ matrix.config.runtime }}/publish/*
