name: Publish

on:
  push:
    tags: '**'

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release_step.outputs.upload_url }}
    steps:
      - name: Create a Release
        id: create_release_step
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  publish:
    runs-on: ${{ matrix.config.os }}
    needs: create_release

    strategy:
      matrix:
        config:
          - { name: win_x64, os: windows-latest, runtime: win-x64 }
          - { name: win_arm64, os: windows-latest, runtime: win-arm64 }
          - { name: linux_x64, os: ubuntu-latest, runtime: linux-x64 }
          - { name: mac_x64, os: macos-latest, runtime: osx-x64 }
          - { name: mac_arm64, os: macos-latest, runtime: osx-arm64 }

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.config.runtime }}
        working-directory: ./Source/AssetRipper-Console/

      - name: List Files
        shell: bash
        run: ls -R ./Source/AssetRipper-Console/bin/Release/${{ matrix.config.runtime }}/publish

      - name: List Files
        shell: bash
        run: date -u > ./Source/AssetRipper-Console/bin/Release/${{ matrix.config.runtime }}/publish/compile_time.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AssetRipper-Console-${{ matrix.config.runtime }}-${{ github.ref_name }}
          path: |
            ./Source/AssetRipper-Console/bin/Release/${{ matrix.config.runtime }}/publish/${{ matrix.config.executable }}
            ./Source/AssetRipper-Console/bin/Release/${{ matrix.config.runtime }}/publish/*.dll
            ./Source/AssetRipper-Console/bin/Release/${{ matrix.config.runtime }}/publish/*.so
            ./Source/AssetRipper-Console/bin/Release/${{ matrix.config.runtime }}/publish/*.dylib
            ./Source/AssetRipper-Console/bin/Release/${{ matrix.config.runtime }}/publish/compile_time.txt
          if-no-files-found: error

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          name: AssetRipper-Console-${{ matrix.config.runtime }}-${{ github.ref_name }}
          path: artifact
          workflow_conclusion: ""
          skip_unpack: true
      - name: Display artifact
        run: ls -R artifact

      - name: Upload release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./artifact/AssetRipper-Console-${{ matrix.config.runtime }}-${{ github.ref_name }}.zip
          asset_name: AssetRipper-Console-${{ matrix.config.runtime }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip  
